### ISSUE TITLE
Fid-Loader for MP4

### ISSUE THREAD

**Issue by 1nner-Peace** [AurisTFG/Fid-Loader#1]
Hello Auris!
First of all, thank you for your work! Is there any chance, you could port this plugin to Maniaplanet?

**Comment by AurisTFG** [comment]
> Hello Auris! First of all, thank you for your work! Is there any chance, you could port this plugin to Maniaplanet?

**Comment by AurisTFG** [comment]
Hey, I am planning on refactoring the plugin and trying to bring it to Maniaplanet soon. Dont know when yet, maybe later this month

**Comment by AurisTFG** [comment]
Hey, sorry it took that long, I just pushed an update to support both MP4 and Turbo, it should now work whenever the update gets approved 👍
